#!/usr/local/bin/python3
import sys
import os

def add_50(filename):
    bed_file = open(filename,'r')
    for line in bed_file:
        line = line.split("\t")
        line[1] = int(line[1]) - 50
        line[2] = int(line[2]) + 50
        print (line)

def training_testing_sets_separation(filename, ratio, training_file, testing_file):
    """It separete the data set in training and testing"""
    bed50_file = open(filename,"r")
    training = open(training_file, 'w')
    testing = open(testing_file, 'w')
    count = 0
    for line in bed50_file:
        count += 1
        if count % ratio == 0:
            testing.write(line)
        else:
            training.write(line)


def background_signal_separation(filename):
    """It separate from the sequence the background from the signal"""
    bed50_file = open(filename,"r")
    background = ()
    signal =()
    for line in bed50_file:
        line = line.strip().upper().split("\t")
        background += (line[10][:50],)
        background += (line[10][-50:],)
        signal += (line[10][50:-50],)
    return (background, signal)

def generate_kmers(k,y=''):
    """
    This function is a generator of kmers for DNA bases.
    It uses a recursive aproach.
    The only required argument is the order (k).
    it also accepts prefix defined as y='prefix'
    the default value for y is ''.
    example:
        get_kmers(3)
    """
    if k==0:
        yield y
    else:
        for m in ['A','C','T','G']:
            kmer=y+m
            for item in generate_kmers(k-1,kmer):
                yield item


def dictionary_kmers(k):
    """It generates a dictionary for all possible kmers"""
    kmer_dict = {}
    for i in generate_kmers(k):
        kmer_dict[i]=1
    return (kmer_dict)

def get_kmers(sequence,k):
    """From a sequence extract all the possible k-mers in that sequence"""
    kmers_list=[]
    length=len(sequence)
    if k<1 or length < k:
        sys.exit()
    i=0
    while i<length:
#        print(i)
        if len(sequence[i:i+k])==k:
            yield sequence[i:i+k]
        i=i+1


### For simple iterators, yield from iterable is essentially
### just a shortened form of for item in iterable: yield item:

def build_hash(seq_list,k):
    """From a list of sequences it builds a dictionary without pseudocounts"""
    kmer_dict = {}
    for i in seq_list:
        for j in get_kmers(i,k):
            if j in kmer_dict: #dictionary_kmers(2) ?!
                kmer_dict[j]= i.count(j) + kmer_dict[j]
            else:
                kmer_dict[j]=i.count(j)
    for x in generate_kmers(k-1):
        total_length=0
        for y in ['A','C','G','T']:
            if x+y in kmer_dict:
                total_length=total_length+kmer_dict[x+y]
            else:
                pass
        for y in ['A','C','G','T']:
            if x+y in kmer_dict:
                kmer_dict[x+y]=kmer_dict[x+y]/total_length
            else:
                pass
    return kmer_dict

def build_hash_pseudocount(seq_list,k):
    """From a list of sequences it builds a dictionary with pseudocounts"""
    kmer_dict=dictionary_kmers(k)
    for i in seq_list:
        for j in get_kmers(i,k):
            kmer_dict[j]= i.count(j) + kmer_dict[j]
    for x in generate_kmers(k-1):
        total_length=0
        for y in ['A','C','G','T']:
            total_length=total_length+kmer_dict[x+y]
        for y in ['A','C','G','T']:
            kmer_dict[x+y]=kmer_dict[x+y]/total_length
    return kmer_dict


def print_hash(dict_signal,dict_background,outfilename):
    """This function prints the MM in a output file"""
    count=0
    out_file_name=open(outfilename, "w")
    out_file_name.write("This file contains the information of the MM generated by in MMDI:\n")
    out_file_name.write("\tBackground table\n")
    out_file_name.write("bg\tA\tC\tG\tT\n")
    for i in dict_background:
        order=len(i)
        break
    for j in generate_kmers(order-1):
        out_file_name.write("{}\t".format(j))
        for u in  ['A','C','G','T']:
            if j+u in dict_signal:
                out_file_name.write("{:.3f}\t".format(dict_background[j+u]))
            else:
                out_file_name.write("NA\t")
        out_file_name.write("\n")
    out_file_name.write("\tSignal table\n")
    out_file_name.write("fg\tA\tC\tG\tT\n")
    for j in generate_kmers(order-1):
        out_file_name.write("{}\t".format(j))
        for u in  ['A','C','G','T']:
            if j+u in dict_signal:
                out_file_name.write("{:.3f}\t".format(dict_signal[j+u]))
            else:
                out_file_name.write("NA\t")
        out_file_name.write("\n")
if __name__ == '__main__':
    (background, signal) = background_signal_separation("example.bed")
    print("BACKGROUND KMER_DICT \n",build_hash(background,3))
    print ("\n\nSIGNAL KMER_DICT \n", build_hash(signal,3))
